"""Add arguments_string to sk_spider

Revision ID: 475aaf112573
Revises: 25d677da14cd
Create Date: 2026-04-14 09:44:57.146905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '475aaf112573'
down_revision = '25d677da14cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sk_spider', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arguments_string', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sk_spider', schema=None) as batch_op:
        batch_op.drop_column('arguments_string')

    # ### end Alembic commands ###
